const LEGACY_SCREEN_WIDTH = 630;
const LEGACY_SCREEN_HEIGHT = 480;

const SCREEN_WIDTH = 256;
const SCREEN_HEIGHT = 192;
const TILE_SIZE = 16;
const GRID_WIDTH = SCREEN_WIDTH / TILE_SIZE;
const GRID_HEIGHT = SCREEN_HEIGHT / TILE_SIZE;

const LEGACY_BLOCK_SIZE = { width: 30, height: 30 };
const PLAYER_SIZE = TILE_SIZE;

export const PORT_CONFIG = {
    LEGACY_SCREEN_WIDTH,
    LEGACY_SCREEN_HEIGHT,
    SCREEN_WIDTH,
    SCREEN_HEIGHT,
    TILE_SIZE,
    GRID_WIDTH,
    GRID_HEIGHT,
};

export { LEGACY_BLOCK_SIZE, PLAYER_SIZE };
